### ISSUE TITLE
Compatibility with React-Three-Fiber/Drei, OR clipping in web-ifc-three

### ISSUE THREAD

**Issue by Triazic** [IFCjs/web-ifc-viewer#144]
I want to use the clipping planes and post-processing features of web-ifc-viewer but am currently using react-three-fiber and web-ifc-three. 

I do not want to throw away all of my code and start again using web-ifc-viewer as the base. I want the base to remain as React-Three-Fiber. I tried porting the clipping function from this library but it's very, very gummed up in the viewer logic (IfcContext etc).

So is there a way to:
a) use web-ifc-viewer in a way that doesn't conflict/compete with react-three-fiber?, or
b) use this library's clipping and post-production niceties in web-ifc-three

**Comment by harrycollin** [comment]
I think you'd have to take the clipping planes and/or any other component from web-ifc-viewer and adapt them for react-three-fiber. Unfortunately they are closely tied to use parts of web-ifc-viewer, such as context. But it shouldn't be much work to adapt them. Clipping planes especially don't need much work in order to allow them to work outside of web-ifc-viewer.

**Comment by agviegas** [comment]
Hey, we are now porting all the BIM tools [to a new repository](https://github.com/IFCjs/components) where each tool should end up quite decoupled. We'll port the clipping planes asap. Hopefully, that will make this (and bringing other tools to your project) easier. Cheers!
