### ISSUE TITLE
Progressive model loading

### ISSUE THREAD

**Issue by cesarecaoduro** [IFCjs/web-ifc-viewer#96]
Is it possible to have a progressive loading of the scene?
As soon as an object is parsed is added to the scene. This, together with the existing loading progress, will improve a lot the user experience (especially if the parsing happens in a separate thread)

**Comment by agviegas** [comment]
This is not possible with .ifc files. But remember that IFC is not the file itself, but the schema 😃 As you might now, what we usually call "IFC" is a STEP file, which is very uncomfortable to work with, because it makes it mandatory to load the whole thing at once.

This is obviously not convenient nor scalable, so now we have decided to start developing a new workflow that allows to convert an IFC to one or many glTF files (for geometry) and one or many JSON files (for properties). You can check the [export example](https://github.com/IFCjs/hello-world/tree/main/examples/web-ifc-viewer/gltf-export) and the [import example](https://github.com/IFCjs/hello-world/tree/main/examples/web-ifc-viewer/gltf-import). 

That has numerous advantages, and one of them is that things get [loaded progressively](https://ifcjs.github.io/hello-world/examples/web-ifc-viewer/gltf-import/), like you say ☺ So I'd say that this is solved!
