### ISSUE TITLE
More verbose errors

### ISSUE THREAD

**Issue by cesarecaoduro** [IFCjs/web-ifc-viewer#97]
It looks like the error are not very descriptive. Can we change this to have some we can actually parse in a log file or in a log report on the main front-end?
```
const model = await viewer.IFC.loadIfc(
        ifcFile,
        true,
        (err) => {
            console.log(err);
        }
    );
```

![2021-12-01 07_20_44-Window](https://user-images.githubusercontent.com/26373891/144122329-92d9175c-8bc3-4600-b9ac-ace1a2864e21.jpg)

**Comment by agviegas** [comment]
We will progressively improve error handling, but it's going to be as the library progresses 😃 I'm closing this because it's too generic for an issue, but feel free to let us know of specific errors where you don't get enough information back. We are working on those geometric error logs in web-ifc right now!
